name: Competitive Programming Updates

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: gh-pages

      - name: Fetch data
        id: CP-Updates
        uses: fjogeleit/http-request-action@master
        with:
          url: "https://clist.by/coder/glen17/ratings/"
          method: "GET"

      - name: Update data
        run: echo "${{ steps.CP-Updates.outputs.response.data }}" > data/contests.json

      - name: Show file content
        run: cat data/contests.json

      - name: Commit contests data
        uses: EndBug/add-and-commit@v9
        with:
          add: data/contests.json
          message: "Update contests data"
