name: Competitive Programming Updates

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: gh-pages

      - name: Fetch & Update data
        run: |
          curl https://clist.by/coder/glen17/ratings/ > data/contests.json

      - name: Show file content
        run: cat data/contests.json

      - name: Commit contests data
        uses: EndBug/add-and-commit@v9
        with:
          add: data/contests.json
          message: "Update contests data"
